name: ssh_terminal
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  dartssh2: ^2.8.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  shared_preferences: ^2.3.1
  sqlite3: ^3.1.1
  toast: ^0.3.0
  xterm: ^4.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path_android: "assets/launcher.png"
  image_path_ios: "assets/launcher.png"
  android: true
  ios: true
flutter:
  uses-material-design: true